# Generated by Django 2.2.9 on 2020-02-10 07:35

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(default='empty'),
            preserve_default=False,
        ),
    ]
