# Generated by Django 2.2.9 on 2020-02-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
