# Generated by Django 2.2.9 on 2020-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_views',
            field=models.IntegerField(null=True),
        ),
    ]
